# Generated by Django 3.2 on 2021-04-29 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_ok_time_start', models.DateTimeField(blank=True, null=True)),
                ('alert_ok_time_end', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_carrier', models.CharField(blank=True, max_length=30, null=True)),
                ('alarm_on', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issued_Alarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_trigger', models.TextField(null=True)),
                ('alarm_setpoint', models.FloatField(null=True)),
                ('trigger_value', models.FloatField(null=True)),
                ('trigger_time', models.DateTimeField(null=True)),
                ('alarm_sent', models.BooleanField(null=True)),
                ('alarm_still_active', models.BooleanField(null=True)),
                ('seen_on_website', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afterbay_hi', models.FloatField(default=None, null=True)),
                ('afterbay_lo', models.FloatField(default=None, null=True)),
                ('oxbow_deviation', models.FloatField(default=None, null=True)),
                ('r4_hi', models.IntegerField(default=None, null=True)),
                ('r4_lo', models.IntegerField(default=None, null=True)),
                ('r30_hi', models.IntegerField(default=None, null=True)),
                ('r30_lo', models.IntegerField(default=None, null=True)),
                ('r11_hi', models.IntegerField(default=None, null=True)),
                ('r11_lo', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
