# Generated by Django 4.0.4 on 2024-11-22 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(default=None, null=True)),
                ('R4_Flow', models.FloatField(default=None, null=True)),
                ('R5L_Flow', models.FloatField(default=None, null=True)),
                ('R11_Flow', models.FloatField(default=None, null=True)),
                ('R30_Flow', models.FloatField(default=None, null=True)),
                ('UnitsAbbreviation', models.TextField(default=None, null=True)),
                ('Afterbay_Elevation', models.FloatField(default=None, null=True)),
                ('Afterbay_Elevation_Setpoint', models.FloatField(default=None, null=True)),
                ('Oxbow_Gov_Setpoint', models.FloatField(default=None, null=True)),
                ('Oxbow_Power', models.FloatField(default=None, null=True)),
                ('Hell_Hole_Elevation', models.FloatField(default=None, null=True)),
                ('GEN_MDFK_and_RA', models.FloatField(default=None, null=True)),
                ('ADS_MDFK_and_RA', models.FloatField(default=None, null=True)),
                ('ADS_Oxbow', models.FloatField(default=None, null=True)),
                ('Pmin', models.FloatField(default=None, null=True)),
                ('Pmax', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'pi_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeleryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('FORECAST_ISSUED', models.DateTimeField(default=None, null=True)),
                ('GMT', models.DateTimeField(default=None, null=True)),
                ('R4_fcst', models.FloatField(default=None, null=True)),
                ('R30_fcst', models.FloatField(default=None, null=True)),
                ('R11_fcst', models.FloatField(default=None, null=True)),
                ('R20_fcst', models.FloatField(default=None, null=True)),
                ('MFRA_fcst', models.FloatField(default=None, null=True)),
                ('Pmin', models.FloatField(default=None, null=True)),
                ('Pmax', models.FloatField(default=None, null=True)),
                ('Abay_AF_Observed', models.FloatField(default=None, null=True)),
                ('Abay_AF_Change_Observed', models.FloatField(default=None, null=True)),
                ('RA_MW', models.FloatField(default=None, null=True)),
                ('MF_MW', models.FloatField(default=None, null=True)),
                ('Oxbow_fcst', models.FloatField(default=None, null=True)),
                ('Oxbow_Outflow', models.FloatField(default=None, null=True)),
                ('R5L_Value', models.FloatField(default=None, null=True)),
                ('RA_Inflow', models.FloatField(default=None, null=True)),
                ('MF_Inflow', models.FloatField(default=None, null=True)),
                ('Ibay_Spill', models.FloatField(default=None, null=True)),
                ('R20_fcst_adjusted', models.FloatField(default=None, null=True)),
                ('Abay_Inflow', models.FloatField(default=None, null=True)),
                ('Abay_Outflow', models.FloatField(default=None, null=True)),
                ('Abay_AF_Change', models.FloatField(default=None, null=True)),
                ('Abay_AF_Change_Error', models.FloatField(default=None, null=True)),
                ('Abay_CFS_Error', models.FloatField(default=None, null=True)),
                ('Abay_AF_Fcst', models.FloatField(default=None, null=True)),
                ('Abay_Elev_Fcst', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'forecast_data',
            },
        ),
        migrations.CreateModel(
            name='Recreation_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_year_type', models.TextField(default='above_normal', null=True)),
                ('today_recStart', models.DateTimeField(default=None, null=True)),
                ('today_recEnd', models.DateTimeField(default=None, null=True)),
                ('tomorrow_recStart', models.DateTimeField(default=None, null=True)),
                ('tomorrow_recEnd', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_ok_time_start', models.DateTimeField(blank=True, null=True)),
                ('alert_ok_time_end', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_carrier', models.CharField(blank=True, max_length=30, null=True)),
                ('alarm_on', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issued_Alarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_trigger', models.TextField(null=True)),
                ('alarm_setpoint', models.FloatField(null=True)),
                ('trigger_value', models.FloatField(null=True)),
                ('trigger_time', models.DateTimeField(null=True)),
                ('alarm_sent', models.BooleanField(null=True)),
                ('alarm_still_active', models.BooleanField(null=True)),
                ('seen_on_website', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afterbay_hi', models.FloatField(default=None, null=True)),
                ('afterbay_lo', models.FloatField(default=None, null=True)),
                ('oxbow_deviation', models.FloatField(default=None, null=True)),
                ('rampup_oxbow', models.IntegerField(default=None, null=True)),
                ('rampdown_oxbow', models.IntegerField(default=None, null=True)),
                ('r4_hi', models.IntegerField(default=None, null=True)),
                ('r4_lo', models.IntegerField(default=None, null=True)),
                ('r30_hi', models.IntegerField(default=None, null=True)),
                ('r30_lo', models.IntegerField(default=None, null=True)),
                ('r11_hi', models.IntegerField(default=None, null=True)),
                ('r11_lo', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
