# Generated by Django 3.2 on 2021-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recreation_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_year_type', models.TextField(default='above_normal', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='rafting_rampdown_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='rafting_rampup_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
