# Generated by Django 3.2 on 2021-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0002_auto_20210625_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation_data',
            name='water_year_type',
            field=models.TextField(default=None, null=True),
        ),
    ]
