# Generated by Django 3.2 on 2021-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0003_alter_recreation_data_water_year_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation_data',
            name='water_year_type',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
