# Generated by Django 3.2 on 2021-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0005_alter_recreation_data_water_year_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreation_data',
            name='today_rampDown',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recreation_data',
            name='today_rampUp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
