# Generated by Django 3.2 on 2021-06-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0008_auto_20210629_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recreation_data',
            old_name='today_rampDown',
            new_name='today_recEnd',
        ),
        migrations.RenameField(
            model_name='recreation_data',
            old_name='today_rampUp',
            new_name='today_recStart',
        ),
    ]
