# Generated by Django 3.2 on 2021-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbayDashboard', '0009_auto_20210629_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreation_data',
            name='tomorrow_recEnd',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recreation_data',
            name='tomorrow_recStart',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
